---
  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: kube-monkey
    namespace: kube-system
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: kube-monkey
      spec:
        containers:
          -  name: kube-monkey
             command:
               - "/kube-monkey"
             image: ricjcosme/kube-monkey
             volumeMounts:
               - name: config-volume
                 mountPath: "/etc/kube-monkey"
             livenessProbe:
               successThreshold: 1
               failureThreshold: 3
               httpGet:
                 path: /healthz
                 port: 8080
                 scheme: HTTP
               initialDelaySeconds: 10
               periodSeconds: 10
        volumes:
          - name: config-volume
            configMap:
              name: kube-monkey-config-map
